// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBTjZb1ULQBbI5UIbv6D1I9xvymhVZwras",
      authDomain: "datenightlive-7c307.firebaseapp.com",
      projectId: "datenightlive-7c307",
      storageBucket: "datenightlive-7c307.appspot.com",
      messagingSenderId: "380678109482",
      appId: "1:380678109482:android:10ebda59433a0f383a0653"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTjZb1ULQBbI5UIbv6D1I9xvymhVZwras',
    appId: '1:380678109482:android:10ebda59433a0f383a0653',
    messagingSenderId: '380678109482',
    projectId: 'datenightlive-7c307',
    storageBucket: 'datenightlive-7c307.appspot.com',  
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTjZb1ULQBbI5UIbv6D1I9xvymhVZwras',
    appId: '1:380678109482:android:10ebda59433a0f383a0653',
    messagingSenderId: '380678109482',
    projectId: 'datenightlive-7c307',
    storageBucket: 'datenightlive-7c307.appspot.com',  
    iosBundleId: 'com.emma.DNL',
  );
}
